# Generated by Django 5.2.5 on 2025-09-19 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="subscriptions_to_journalists",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="subscriptions_to_publishers",
        ),
        migrations.AddField(
            model_name="customuser",
            name="subscribed_journalists",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="subscribed_publishers",
            field=models.ManyToManyField(
                blank=True, related_name="subscribed_readers", to="articles.publisher"
            ),
        ),
    ]
